### ISSUE TITLE
License

### ISSUE THREAD

**Issue by solson** [solson/rust-nightly-nix#1]
@Ericson2314 This is primarily your code. What do you want the license to be?

**Comment by Ericson2314** [comment]
Dual MIT and Apache is fine. On a different note, I'm kind of a history buff, could you use the full history I just spliced together from https://github.com/Ericson2314/rust-nightly-nix :)?

**Comment by solson** [comment]
Both done. I also restructured my own commits, so your fork won't be able to pull from mine cleanly, but the history is much cleaner.
