### ISSUE TITLE
Looking for a new maintainer, otherwise abandoning

### ISSUE THREAD

**Issue by solson** [solson/rust-nightly-nix#27]
I have not used rust-nightly-nix for years now. The [mozilla overlay](https://github.com/mozilla/nixpkgs-mozilla) worked better, from what I can remember, and I just use `rustup` now that the Nix package makes it do `patchelf` automatically.

In a couple weeks I'm going to archive this repo and close the open issues/PRs as stale, unless someone else wants to pick up maintainership (in which case I'd like to transfer the repo to your account).

cc @Ericson2314

**Comment by solson** [comment]
(Apologies to everyone whose issues and PRs I have ignored. It was not intentional and I eventually forgot to check back.)

**Comment by Ericson2314** [comment]
Archiving is fine with me, I use https://github.com/mozilla/nixpkgs-mozilla too. https://github.com/mozilla/nixpkgs-mozilla/pull/222 fixed the only issues I had with it.

**Comment by solson** [comment]
Ok, archiving the repo now. If anyone has any further comments they can email me.
