### ISSUE TITLE
Example using rust-std and rustcWithSysroots

### ISSUE THREAD

**Issue by flosse** [solson/rust-nightly-nix#6]
Would you mind to add a little example how to use `rust-std` and `rustcWithSysroots`?
Thanks a lot!

**Comment by Ericson2314** [comment]
https://github.com/QuiltOS/QuiltOS/blob/master/default.nix#L7-L41 If you want to distill that into a PR for README, please do!

**Comment by flosse** [comment]
awesome! `cargo build --target x86_64-unknown-linux-mus` just works :)

**Comment by flosse** [comment]
BTW: Do you know an example for cross-compiling with nixos?
At least building for a Raspberry (`cargo build --target arm-unknown-linux-musleabihf`) would be great :)

**Comment by flosse** [comment]
> If you want to distill that into a PR for README, please do!

done in #7 :)

**Comment by Ericson2314** [comment]
@flosse what's the question? cross compiling non-rust stuff with NixOS? Actually I'm working on that these days too---unfortunately at the moment its pretty shabby.

**Comment by flosse** [comment]
> what's the question? cross compiling non-rust stuff with NixOS?

No, just cross-compiling rust stuff with NixOS.

**Comment by Ericson2314** [comment]
Is everything here now resolved?

**Comment by flosse** [comment]
> Is everything here now resolved?

Almost everything... I'm still interested in cross-compile solutions, but that's an other topic ;-)
