### ISSUE TITLE
Problems with openssl

### ISSUE THREAD

**Issue by eb4890** [solson/rust-nightly-nix#8]
I'm trying to compile a rust project that relies on openssl  and nightly and I'm hitting problems using your module.

It had previously been working with this module (alsomething weird like the modules had to be downloaded without nix-shell -p openssl and it had to be compiled with it). It might have been a change in my openssl module that broke it.

An example repo can be found here https://github.com/eb4890/ssl-problems

Trying a cargo build with and without nix-shell -p openssl results in 

``
error: failed to run custom build command for `openssl-sys-extras v0.7.14`
process didn't exit successfully: `/home/loadquo/src/ssl-problems/target/debug/build/openssl-sys-extras-5c7e4d8925825f00/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
PROFILE = Some("debug")
TARGET = Some("x86_64-unknown-linux-gnu")
debug=true opt-level=0
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-m64" "-fPIC" "-o" "/home/loadquo/src/ssl-problems/target/debug/build/openssl-sys-extras-5c7e4d8925825f00/out/src/openssl_shim.o" "-c" "src/openssl_shim.c"
cargo:warning=src/openssl_shim.c:1:26: fatal error: openssl/hmac.h: No such file or directory
cargo:warning=compilation terminated.
ExitStatus(ExitStatus(256))

command did not execute successfully, got: exit code: 1
``
I've got further by specifying the OPENSSL_INCLUDE_DIR. Now I get link errors.

[nix-shell:~/src/ssl-problems]$ OPENSSL_INCLUDE_DIR=/nix/store/gm5k8wac101czg1l9kkmlydzyd2dh2f1-openssl-1.0.2h-dev/include cargo build
   Compiling ssl-problems v0.1.0 (file:///home/loadquo/src/ssl-problems)
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/nix/store/1y5y1n1ma2fd287j7blr4rz5bm7kadic-rust-nightly-2016-11-06/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/loadquo/src/ssl-problems/target/debug/ssl_problems.0.o" "-o" "/home/loadquo/src/ssl-problems/target/debug/ssl_problems" "-Wl,--gc-sections" "-pie" "-nodefaultlibs" "-L" "/home/loadquo/src/ssl-problems/target/debug/deps" "-L" "/home/loadquo/src/ssl-problems/target/debug/build/openssl-5464f8f6e728c35a/out" "-L" "/home/loadquo/src/ssl-problems/target/debug/build/openssl-sys-extras-5c7e4d8925825f00/out" "-L" "/nix/store/1y5y1n1ma2fd287j7blr4rz5bm7kadic-rust-nightly-2016-11-06/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "/home/loadquo/src/ssl-problems/target/debug/deps/libopenssl-6d8c7b7707d12a7d.rlib" "/home/loadquo/src/ssl-problems/target/debug/deps/libopenssl_sys_extras-5206753a3d8bd8ef.rlib" "/home/loadquo/src/ssl-problems/target/debug/deps/liblazy_static-7f1b96a3a3eb529d.rlib" "/home/loadquo/src/ssl-problems/target/debug/deps/libbitflags-0e272044714c8076.rlib" "/home/loadquo/src/ssl-problems/target/debug/deps/libopenssl_sys-a4f86492ba1e2f09.rlib" "/home/loadquo/src/ssl-problems/target/debug/deps/liblibc-ad32fde1bd850538.rlib" "/nix/store/1y5y1n1ma2fd287j7blr4rz5bm7kadic-rust-nightly-2016-11-06/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-6eb85298.rlib" "/nix/store/1y5y1n1ma2fd287j7blr4rz5bm7kadic-rust-nightly-2016-11-06/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-6eb85298.rlib" "/nix/store/1y5y1n1ma2fd287j7blr4rz5bm7kadic-rust-nightly-2016-11-06/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-6eb85298.rlib" "/nix/store/1y5y1n1ma2fd287j7blr4rz5bm7kadic-rust-nightly-2016-11-06/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-6eb85298.rlib" "/nix/store/1y5y1n1ma2fd287j7blr4rz5bm7kadic-rust-nightly-2016-11-06/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-6eb85298.rlib" "/nix/store/1y5y1n1ma2fd287j7blr4rz5bm7kadic-rust-nightly-2016-11-06/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_unicode-6eb85298.rlib" "/nix/store/1y5y1n1ma2fd287j7blr4rz5bm7kadic-rust-nightly-2016-11-06/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-6eb85298.rlib" "/nix/store/1y5y1n1ma2fd287j7blr4rz5bm7kadic-rust-nightly-2016-11-06/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-6eb85298.rlib" "/nix/store/1y5y1n1ma2fd287j7blr4rz5bm7kadic-rust-nightly-2016-11-06/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-6eb85298.rlib" "/nix/store/1y5y1n1ma2fd287j7blr4rz5bm7kadic-rust-nightly-2016-11-06/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-6eb85298.rlib" "/nix/store/1y5y1n1ma2fd287j7blr4rz5bm7kadic-rust-nightly-2016-11-06/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-6eb85298.rlib" "-l" "ssl" "-l" "crypto" "-l" "util" "-l" "dl" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "util"
  = note: /nix/store/d61gfhj50bfrrlvp4jzdxmsap3izsvyc-binutils-2.27/bin/ld: cannot find -lssl
/nix/store/d61gfhj50bfrrlvp4jzdxmsap3izsvyc-binutils-2.27/bin/ld: cannot find -lcrypto
collect2: error: ld returned 1 exit status

error: aborting due to previous error

I'm personally not sure how to go about fixing things. I've tried adding openssl to the rpath, but that hasn't helped.

Everything I've seen says not to use makeWrapper which I would be tempted to.

**Comment by eb4890** [comment]
I can bodge around it by specifying a LIBRARY_PATH in the environment. Not exactly ideal though.

**Comment by evanjs** [comment]
`nix-shell -p openssl.dev` or adding `openssl.dev` to `buildInputs` in `shell.nix` should work for others experiencing this issue.

**Comment by eb4890** [comment]
Thanks for the help @evanjs
