### ISSUE TITLE
Coercion Error

### ISSUE THREAD

**Issue by ethanpailes** [solson/rust-nightly-nix#9]
I'm having a hard time getting this nix expression to do anything but complain that it can't coerce a function into a string. I have tried following the examples in the readme to the best of my abilities, and the build always fails with some variation of the following error message.

```
error: while evaluating the attribute ‘nativeBuildInputs’ of the derivation ‘test-pac
kage’ at /home/ethan/repos/mucking/gluon-shell/default.nix:8:7:                     
cannot coerce a function to a string, at /home/ethan/repos/mucking/gluon-shell/defaul
t.nix:8:7               
```

Here is a minimal default.nix which can produce the error message (rust-nightly.nix is in the support directory):

```
with import <nixpkgs> {
};
let rustNightly = pkgs.callPackage ./support/rust-nightly.nix {};
 in 
{
  testEnv = stdenv.mkDerivation {
      buildInputs = [ rustNightly.rust ];
      name = "test-package";
  };
}
```

rewriting the default.nix to use package overrides also fails:

```
with import <nixpkgs> {
    config.packageOverrides = pkgs: {
        rustNightly = pkgs.callPackage ./support/rust-nightly.nix {};
    };
};
{
  testEnv = stdenv.mkDerivation {
      name = "test-package";
      buildInputs = [ pkgs.rustNightly.rust ];
  };
}
```

I have tried this on both NixOS and OS X.

Is there a specific version of `nixpkgs` that I should be using? I have tried this on both the current master and the release-16.03 branch.

**Comment by Ericson2314** [comment]
`rustNightly.rust` is a function :); take another read of the readme. 

"String" here is an awkward error message--what's really going on is it expects a derivation, which is then turned to a string (i.e. "/nix/store/..."). Unfortunately no error occurs until the attempted conversion to string.

**Comment by Ericson2314** [comment]
Feel free to comment with suggestions on how to make this more obvious!

**Comment by ethanpailes** [comment]
Thanks a bunch! I replaced pkgs.rustNightly.rust with (pkgs.rustNightly.rust {}) and everything seems to be working fine. I think this is just an instance of me struggling with how dynamic nix is. I will open a PR with some changes to the readme that I think might have helped me not be so silly in the first place, and you can see if you agree with me.
